spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

token:
  secret: d5c4471eee7a457e8291118bca7b1721
